model_parameters:
  name: "MDN-RNN"
  hidden_size: 32

experiment_parameters:
  dataset: gui-dataset
  data_path: "datasets/gui_env/random-widgets/2021-12-27_22-10-07/0"
  batch_size: 10
  sequence_length: 16
  learning_rate: 0.0001
  max_epochs: 5
  manual_seed: 100

vae_parameters:
  directory: "logs/vae/gui-dataset/VAE/version_2"

trainer_parameters:
  gpu: -1
  num_workers: 0

logging_parameters:
  debug: False
  save_dir: "logs/vae/"
