from models.vae.with_max_pool.large_filter_sizes_maxpool_vae import LargeFilterSizesMaxPoolVAE
from models.vae.with_max_pool.small_filter_sizes_maxpool_vae import SmallFilterSizesMaxPoolVAE
from models.vae.with_max_pool.decreasing_filter_sizes_maxpool_vae import DecreasingFilterSizesMaxPoolVAE

from models.vae.with_max_pool.small_filter_sizes_small_bottleneck_maxpool_vae import (
    SmallFilterSizesSmallBottleneckMaxPoolVAE)
from models.vae.with_max_pool.small_filter_sizes_small_bottleneck_maxpool_vae_2 import (
    SmallFilterSizesSmallBottleneckMaxPoolVAE2)
from models.vae.with_max_pool.small_filter_sizes_small_bottleneck_maxpool_vae_3 import (
    SmallFilterSizesSmallBottleneckMaxPoolVAE3)
from models.vae.with_max_pool.small_filter_sizes_small_bottleneck_maxpool_vae_4 import (
    SmallFilterSizesSmallBottleneckMaxPoolVAE4)

from models.vae.with_max_pool.half_input_small_filter_sizes_small_bottleneck_maxpool_vae import (
    HalfInputSmallFilterSizesSmallBottleneckMaxPoolVAE
)

from models.vae.with_max_pool.half_input_small_filter_sizes_with_stride_maxpool_vae import (
    HalfInputSmallFilterSizesWithStrideMaxPoolVAE
)
