from models.vae.no_max_pool.large_filter_sizes_vae import LargeFilterSizesVAE
from models.vae.no_max_pool.large_filter_sizes_vae_2 import LargeFilterSizesVAE2
from models.vae.no_max_pool.small_filter_sizes_vae import SmallFilterSizesVAE
from models.vae.no_max_pool.decreasing_filter_sizes_vae import DecreasingFilterSizesVAE

from models.vae.no_max_pool.small_filter_sizes_small_bottleneck_vae import SmallFilterSizesSmallBottleneckVAE
from models.vae.no_max_pool.small_filter_sizes_small_bottleneck_vae_2 import SmallFilterSizesSmallBottleneckVAE2
from models.vae.no_max_pool.small_filter_sizes_small_bottleneck_vae_3 import SmallFilterSizesSmallBottleneckVAE3

from models.vae.no_max_pool.half_input_small_filter_sizes_small_bottleneck_vae import (
    HalfInputSmallFilterSizesSmallBottleneckVAE
)
from models.vae.no_max_pool.half_input_small_filter_sizes_small_bottleneck_vae_2 import (
    HalfInputSmallFilterSizesSmallBottleneckVAE2
)
