model_parameters:
  name: "small_filter_sizes_small_bottleneck_3"
  activation_function: "relu"
  output_activation_function: "tanh"
  hidden_dimensions: [32, 64, 128, 256, 512, 512, 1024, 2048]
  latent_size: 50
  input_channels: 3
  batch_norm: False
  disable_kld: False
  kld_weight: 0.00001
  kld_warmup: True
  kld_warmup_batch_count: 2000
  kld_warmup_skip_batches: 0

experiment_parameters:
  dataset: "gui_env_image_dataset"
  dataset_path: "path-to-dataset"
  img_size: 448
  batch_size: 32
  learning_rate: 0.0001
  max_epochs: 20
  manual_seed: 1010
  optimizer: "adam"

lr_scheduler:
  use_lr_scheduler: True
  mode: "min"
  patience: 5
  factor: 0.1
  threshold: 0.001
  threshold_mode: "abs"

trainer_parameters:
  gpu: -1
  num_workers: 0

logging_parameters:
  debug: False
  save_model_checkpoints: True
  scalar_log_frequency: 20
  image_epoch_log_frequency: 5
  save_dir: "logs/vae/"
