model_parameters:
  name: "vae_full_input_size"
  activation_function: "leaky_relu"
  output_activation_function: "tanh"
  hidden_dimensions: [8, 16, 32, 64, 128]
  latent_size: 256
  input_channels: 3
  batch_norm: True
  disable_kld: False
  kld_weight: 1.0
  kld_warmup: True
  kld_warmup_batch_count: 4000
  kld_warmup_skip_batches: 2000

experiment_parameters:
  dataset: "gui_env_image_dataset"
  dataset_path: "path-to-split-dataset"
  img_size: 448
  batch_size: 10
  learning_rate: 0.005
  max_epochs: 5
  manual_seed: 1010

lr_scheduler:
  use_lr_scheduler: True
  mode: "min"
  patience: 5
  factor: 0.25
  threshold: 0.001

trainer_parameters:
  gpu: -1
  num_workers: 0

logging_parameters:
  debug: False
  save_model_checkpoints: True
  scalar_log_frequency: 20
  image_epoch_log_frequency: 5
  save_dir: "logs/vae/"
