model_parameters:
  name: "vae_full_input_size"
  activation_function: "leaky_relu"
  hidden_dimensions: [8, 16, 32, 64, 128]
  latent_size: 256
  input_channels: 3
  batch_norm: True
  kld_weight: 1.0
  kld_warmup: True

experiment_parameters:
  dataset: multiple_sequences_vae
  dataset_path: "/home/pdeubel/PycharmProjects/data/test-gui"
  img_size: 448
  batch_size: 10
  learning_rate: 0.005
  max_epochs: 5
  manual_seed: 1010

trainer_parameters:
  gpu: -1
  num_workers: 0

logging_parameters:
  debug: False
  scalar_log_frequency: 20
  image_epoch_log_frequency: 5
  save_dir: "logs/vae/"
