model_parameters:
  name: "vae_full_input_size"
  latent_size: 256
  input_channels: 3

experiment_parameters:
  dataset: multiple_sequences_vae
  dataset_path: "/home/pdeubel/PycharmProjects/data/test-gui"
  img_size: 448
  batch_size: 10
  learning_rate: 0.005
  kld_weight: 1.0
  kld_warmup: True
  max_epochs: 5
  manual_seed: 1010

trainer_parameters:
  gpu: -1
  num_workers: 0

logging_parameters:
  debug: False
  save_dir: "logs/vae/"
